// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9HwFFM9apNkgWHVTmWL6gon_PFCsMZY',
    appId: '1:729829703364:web:fdb30d34061d96e9419391',
    messagingSenderId: '729829703364',
    projectId: 'chat-3a33d',
    authDomain: 'chat-3a33d.firebaseapp.com',
    storageBucket: 'chat-3a33d.appspot.com',
    measurementId: 'G-TK4HL9DKQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuiWLrukIgUaeOO6ZDI9osxmX1S6TjRGg',
    appId: '1:729829703364:android:69d42f9b55a83c59419391',
    messagingSenderId: '729829703364',
    projectId: 'chat-3a33d',
    storageBucket: 'chat-3a33d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-ls7znGbw8oTJ4ZqL87DQ_mcDx_gDayU',
    appId: '1:729829703364:ios:38647927c861a734419391',
    messagingSenderId: '729829703364',
    projectId: 'chat-3a33d',
    storageBucket: 'chat-3a33d.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-ls7znGbw8oTJ4ZqL87DQ_mcDx_gDayU',
    appId: '1:729829703364:ios:ea06f1492c3748e4419391',
    messagingSenderId: '729829703364',
    projectId: 'chat-3a33d',
    storageBucket: 'chat-3a33d.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
